name: Metrics-Agent

on: [push]

jobs:

  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - uses: snyk/actions/setup@master
      - uses: actions/checkout@v2
      - name: Snyk Test
        run: snyk test  --severity-threshold=medium --org=cloudability
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk monitor
        run: snyk monitor --org=cloudability
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - uses: actions/checkout@v2
      - name: Install tools
        run: make install-tools
      - name: Lint
        run: make lint
      - name: Run Tests
        run: make test

  test_e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - uses: actions/checkout@v2
      - name: run e2e tests
        run: make test-e2e-all
